const express = require("express");
const { register, login, getMe, updateProfile, getUserProfile, getTalent, getMentors, verifyOTP, resendOTP, forgotPasswordOTP, loginWithOTP, deleteAccount, changePassword } = require("../controllers/authController");
const { protect } = require("../middleware/authMiddleware");
const router = express.Router();
router.post("/register", register);
router.post("/login", login);
router.post("/verify-otp", protect, verifyOTP);
router.post("/resend-otp", protect, resendOTP);
router.post("/forgot-password-otp", forgotPasswordOTP);
router.post("/login-otp", loginWithOTP);
router.get("/me", protect, getMe);
router.put("/update-profile", protect, updateProfile);
router.put("/change-password", protect, changePassword);
router.delete("/delete-account", protect, deleteAccount);
router.get("/profile/:id", getUserProfile);
router.get("/talent", protect, getTalent);
router.get("/mentors", getMentors);
module.exports = router;
